### PR TITLE
Include pyyaml and ignore initiated ymal file

### PR DESCRIPTION
**Pull request by edxu96**
closing #73

### CODE REVIEW

**Comment by zequnyu** [comment]
Do we need to exclude `src/cmdict/data/extraction.yaml`?

**Comment by edxu96** [comment]
> Do we need to exclude `src/cmdict/data/extraction.yaml`?

I just tried. There is no resulted `extraction.yaml`. All the searched and extracted words are stored in `history.yaml`. Maybe your `src/cmdict/data/extraction.yaml` is from old version.

There is no `--version` option and no information on version in `--help`, by the way. Another issue?

**Comment by zequnyu** [comment]
Seems like you are using it [here](https://github.com/zequnyu/cmdict/blob/7deb0d459ba6710577819714cb2b27f940c1c7c4/src/cmdict/run_script.py#L132).

**Comment by zequnyu** [comment]
Also I think those yaml files should be hidden (starts with `.`).

**Pull request merged**
